config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  root 'tasks#index'
  resources :projects, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :tasks, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :groups, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :people, only: [:index] do
    collection do
      get 'search'
      get 'add_group'
      get 'remove_group'
      get 'add_project'
      get 'remove_project'
      get 'add_task'
      get 'remove_task'
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :email, :password, presence: true
  validates :password, length: { minimum: 6 }

  has_many :administrator_projects, class_name: 'Project', foreign_key: 'administrator_id'
  has_many :administrating_groups, class_name: 'Group', foreign_key: 'administrator_id'
  has_many :group_members, foreign_key: 'member_id'
  has_many :belonged_groups, class_name: 'Group', through: :group_members, source: :group
  has_many :project_members, foreign_key: 'member_id'
  has_many :belonged_projects, class_name: 'Project', through: :project_members, source: :project
  has_many :task_members, foreign_key: 'member_id'
  has_many :tasks, through: :task_members

  def email_required?
    false
  end
  def email_changed?
    false
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  end
  def search
    @people = Person.where.not(id: search_params[:member_ids]).where('nickname LIKE(?)', "#{search_params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def add_group
    @group_member = GroupMember.new(group_member_params)
    @group_member.save
  end
  
  def remove_group
    @group_member = GroupMember.where(group_id: group_member_params[:group_id]).where(member_id: group_member_params[:member_id])
    @group_member.delete_all
  end

  def add_project
    @project_member = ProjectMember.new(project_member_params)
    @project_member.save
  end

  def remove_project
    @project_member = ProjectMember.where(project_id: project_member_params[:project_id]).where(member_id: project_member_params[:member_id])
    @project_member.delete_all
  end

  def add_task
    @task_member = TaskMember.new(task_member_params)
    @task_member.save
  end

  def remove_task
    @task_member = TaskMember.where(task_id: task_member_params[:task_id]).where(member_id: task_member_params[:member_id])
    @task_member.delete_all
  end

  private
  def search_params
    params.permit(:keyword, { member_ids: [] })
  end

  def group_member_params
    params.permit(:group_id).merge(member_id: current_person.id)
  end

  def project_member_params
    params.permit(:project_id).merge(member_id: current_person.id)
  end

  def task_member_params
    params.permit(:task_id).merge(member_id: current_person.id)
  end
end

app/views/people/index/_body.html.haml
.main-page__body__form.main-page__body__form--with-sidebar
  .main-page__body__form__group
    .main-page__body__form__group__double-field
      .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--left
        .main-page__body__form__group__double-field__group__field-box
          .main-page__body__form__group__double-field__group__field-box__title
            参加プロジェクト
          = link_to "新規プロジェクト作成", new_project_path, class: "main-page__body__form__group__double-field__group__field-box__btn"
        #project-list.main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box{ data: { save: "true" } }
          - current_person.belonged_projects.each do |project|
            .main-page__body__form__group__double-field__group__field-box__field
              - if project.administrator == current_person
                .main-page__body__form__group__double-field__group__field-box__field__mark
                  管理者
              = link_to project.name, project_path(project.id), class: "main-page__body__form__group__double-field__group__field-box__field__text"
              - unless project.administrator == current_person
                .main-page__body__form__group__double-field__group__field-box__field__btn.main-page__body__form__group__double-field__group__field-box__field__btn--remove{ data: { project: { id: project.id, name: project.name } } }
                  = icon 'fas', 'times', class: "main-page__body__form__group__double-field__group__field-box__field__btn__icon"
      .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--right
        .main-page__body__form__group__double-field__group__field-box
          .main-page__body__form__group__double-field__group__field-box__title
            プロジェクト検索
          .main-page__body__form__group__double-field__group__field-box__field
            %input#project-search-input.main-page__body__form__group__double-field__group__field-box__field__input{ placeholder: "プロジェクト名を検索", type: "text" }
        #project-search-list.main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box
    .main-page__body__form__group__double-field
      .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--left
        .main-page__body__form__group__double-field__group__field-box
          .main-page__body__form__group__double-field__group__field-box__title
            参加グループ
          = link_to "新規グループ作成", new_group_path, class: "main-page__body__form__group__double-field__group__field-box__btn"
        #group-list.main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box{ data: { save: "true" } }
          - current_person.belonged_groups.each do |group|
            .main-page__body__form__group__double-field__group__field-box__field
              - if group.administrator == current_person
                .main-page__body__form__group__double-field__group__field-box__field__mark
                  管理者
              = link_to group.name, group_path(group.id), class: "main-page__body__form__group__double-field__group__field-box__field__text"
              - unless group.administrator == current_person
                .main-page__body__form__group__double-field__group__field-box__field__btn.main-page__body__form__group__double-field__group__field-box__field__btn--remove{ data: { group: { id: group.id, name: group.name } } }
                  = icon 'fas', 'times', class: "main-page__body__form__group__double-field__group__field-box__field__btn__icon"
      .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--right
        .main-page__body__form__group__double-field__group__field-box
          .main-page__body__form__group__double-field__group__field-box__title
            グループ検索
          .main-page__body__form__group__double-field__group__field-box__field
            %input#group-search-input.main-page__body__form__group__double-field__group__field-box__field__input{ placeholder: "グループ名を検索", type: "text" }
        #group-search-list.main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box