config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  root 'tasks#index'
  resources :projects, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :tasks, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :groups, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :people, only: [:index] do
    collection do
      get 'search'
      get 'add_group'
      get 'remove_group'
      get 'add_project'
      get 'remove_project'
      get 'add_task'
      get 'remove_task'
    end
  end
end

app/views/shared/main/_footer.html.haml
.main-page__footer
  .main-page__footer__left
    .main-page__footer__left__copy-right
      = "©︎2019 kurogoro"
  .main-page__footer__right
    = link_to "", class: 'main-page__footer__right__link' do
      = icon 'fas', 'envelope', class: "main-page__footer__right__link__icon"
    = link_to "", class: 'main-page__footer__right__link' do
      = icon 'fab', 'twitter', class: "main-page__footer__right__link__icon"
    = link_to "", class: 'main-page__footer__right__link' do
      = icon 'fab', 'github', class: "main-page__footer__right__link__icon"

app/views/shared/main/_header-btns.html.haml
.main-page__header__right-top
  = form_tag "", method: :get, class: "main-page__header__right-top__form-search" do
    = text_field_tag :keyword, "", placeholder: " プロジェクト名やグループ名を検索", class: "main-page__header__right-top__form-search__input"
    = button_tag type: "submit", class: "main-page__header__right-top__form-search__btn" do
      = icon 'fas', 'search', class: "main-page__header__right-top__form-search__btn__icon"
.main-page__header__right-bottom
  .main-page__header__right-bottom__left
    .main-page__header__right-bottom__left__tag
      .main-page__header__right-bottom__left__tag__header
        = link_to new_group_path, class: 'main-page__header__right-bottom__left__tag__header__link' do
          = icon 'fas', 'users', class: "main-page__header__right-bottom__left__tag__header__link__icon"
          .main-page__header__right-bottom__left__tag__header__link__text
            Group
      %ul.main-page__header__right-bottom__left__tag__menu
        - 5.times do |i|
          %li.main-page__header__right-bottom__left__tag__menu__item
            = link_to "Group#{i} name", "", class: "main-page__header__right-bottom__left__tag__menu__item__link"
        %li.main-page__header__right-bottom__left__tag__menu__item
          = link_to "Group一覧から探す", "", class: "main-page__header__right-bottom__left__tag__menu__item__link"
    .main-page__header__right-bottom__left__tag
      .main-page__header__right-bottom__left__tag__header
        = link_to new_project_path, class: 'main-page__header__right-bottom__left__tag__header__link' do
          = icon 'fas', 'project-diagram', class: "main-page__header__right-bottom__left__tag__header__link__icon"
          .main-page__header__right-bottom__left__tag__header__link__text
            Project
      %ul.main-page__header__right-bottom__left__tag__menu
        - 5.times do |i|
          %li.main-page__header__right-bottom__left__tag__menu__item
            = link_to "Project#{i} name", "", class: "main-page__header__right-bottom__left__tag__menu__item__link"
        %li.main-page__header__right-bottom__left__tag__menu__item
          = link_to "Projectから探す", "", class: "main-page__header__right-bottom__left__tag__menu__item__link"
    .main-page__header__right-bottom__left__tag
      .main-page__header__bottom__left__tag__header
        = link_to "", class: 'main-page__header__right-bottom__left__tag__header__link' do
          = icon 'fas', 'tags', class: "main-page__header__right-bottom__left__tag__header__link__icon"
          .main-page__header__right-bottom__left__tag__header__link__text
            Process
      %ul.main-page__header__right-bottom__left__tag__menu
        - 5.times do |i|
          %li.main-page__header__right-bottom__left__tag__menu__item
            = link_to "Process#{i} name", "", class: "main-page__header__right-bottom__left__tag__menu__item__link"
        %li.main-page__header__right-bottom__left__tag__menu__item
          = link_to "Process一覧から探す", "", class: "main-page__header__right-bottom__left__tag__menu__item__link"
  .main-page__header__right-bottom__right
    - if person_signed_in?
      = link_to "ログアウト", destroy_person_session_path, method: :delete, class: "main-page__header__right-bottom__right__btn"
      = link_to "自分の予定", "", class: "main-page__header__right-bottom__right__btn"
      = link_to "タスク作成", "", class: "main-page__header__right-bottom__right__btn"
    - else
      = link_to "ログイン", new_person_session_path, class: "main-page__header__right-bottom__right__btn"
      = link_to "新規登録", new_person_registration_path, class: "main-page__header__right-bottom__right__btn"

app/views/shared/main/_header-logo.html.haml
= link_to root_path do
  = image_tag 'favicon.ico', alt: "tidy tasks", class: "main-page__header__left__logo"
  .main-page__header__left__title
    = "TIDY TASKS"

app/views/shared/main/_sidebar.html.haml
.main-page__body__sidebar
  = link_to "", class: "main-page__body__sidebar__link" do
    = icon 'fas', 'chart-bar', class: "main-page__body__sidebar__link__icon main-page__body__sidebar__link__icon--active"
  = link_to "", class: "main-page__body__sidebar__link" do
    = icon 'fas', 'chart-line', class: "main-page__body__sidebar__link__icon"
  = link_to "", class: "main-page__body__sidebar__link" do
    = icon 'fas', 'list', class: "main-page__body__sidebar__link__icon"