config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  root 'tasks#index'
  resources :projects, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :tasks, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :groups, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :people, only: [:index] do
    collection do
      get 'search'
      get 'add_group'
      get 'remove_group'
      get 'add_project'
      get 'remove_project'
      get 'add_task'
      get 'remove_task'
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :public_access_id, presence: true

  belongs_to :administrator, class_name: "Person", foreign_key: 'administrator_id'
  has_many :project_groups, dependent: :delete_all
  has_many :groups, through: :project_groups
  has_many :project_members, dependent: :delete_all
  has_many :members, class_name: "Person", through: :project_members, source: :member
  has_many :tasks
  belongs_to_active_hash :public_access
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end
  def create
    if project_save
      redirect_to root_path, notice: 'プロジェクトを作成しました'
    else
      render :new
    end
  end
  def show
    @project = Project.find(show_params[:id])
    if @project.members.include?(current_person)
      @own_tasks = []
      @project.tasks.each do |task|
        @own_tasks << task if task.members.include?(current_person)
      end
    end
  end
  def search
    @projects = Project.where.not(id: search_params[:project_ids]).where('name LIKE(?)', "#{search_params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def create_project_params
    params.require(:project).permit(:name, :detail, :deadline, :public_access_id).merge(administrator_id: current_person.id)
  end
  def create_group_params
    params.require(:project).permit({ group_ids: [] })
  end
  def show_params
    params.permit(:id)
  end
  def search_params
    params.permit(:keyword, { project_ids: [] })
  end
  def project_save
    Project.transaction do
      @project = Project.create!(create_project_params)
      @project.groups << Group.where(id: create_group_params[:group_ids])
      @project.save!
    end
  end
end

app/views/projects/show/_body.html.haml
.main-page__body__form.main-page__body__form--with-sidebar
  .main-page__body__form__group
    .main-page__body__form__group__field
      .main-page__body__form__group__field__label プロジェクト名
      .main-page__body__form__group__field__text
        = @project.name
    .main-page__body__form__group__field
      .main-page__body__form__group__field__label 締切り日
      .main-page__body__form__group__field__text
        = @project.deadline
    .main-page__body__form__group__field
      .main-page__body__form__group__field__label 公開・非公開設定
      .main-page__body__form__group__field__text
        = @project.public_access.name
    .main-page__body__form__group__field
      .main-page__body__form__group__field__label 詳細
      .main-page__body__form__group__field__text
        = @project.detail
  .main-page__body__form__group
    .main-page__body__form__group__double-field
      .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--left
        .main-page__body__form__group__double-field__group__field-box
          .main-page__body__form__group__double-field__group__field-box__title
            参加グループリスト
        .main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box
          - @project.groups.each do |group|
            .main-page__body__form__group__double-field__group__field-box__field
              = link_to group.name, group_path(group.id), class: "main-page__body__form__group__double-field__group__field-box__field__text"
      .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--right
        .main-page__body__form__group__double-field__group__field-box
          .main-page__body__form__group__double-field__group__field-box__title
            参加メンバーリスト
        .main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box
          - @project.members.each do |member|
            .main-page__body__form__group__double-field__group__field-box__field
              - if member == @project.administrator
                .main-page__body__form__group__double-field__group__field-box__field__mark
                  管理者
              .main-page__body__form__group__double-field__group__field-box__field__text
                = member.nickname
  .main-page__body__form__group
    - if @project.members.include?(current_person)
      .main-page__body__form__group__double-field
        .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--left
          .main-page__body__form__group__double-field__group__field-box
            .main-page__body__form__group__double-field__group__field-box__title
              タスク一覧
            = link_to "新規タスク作成", new_task_path, class: "main-page__body__form__group__double-field__group__field-box__btn"
          #task-list.main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box{ data: { save: "true" } }
          - @own_tasks.each do |task|
            .main-page__body__form__group__double-field__group__field-box__field
              = link_to task.name, task_path(task.id), class: "main-page__body__form__group__double-field__group__field-box__field__text"
              .main-page__body__form__group__double-field__group__field-box__field__btn.main-page__body__form__group__double-field__group__field-box__field__btn--remove{ data: { task: { id: task.id, name: task.name } } }
                = icon 'fas', 'times', class: "main-page__body__form__group__double-field__group__field-box__field__btn__icon"
        .main-page__body__form__group__double-field__group.main-page__body__form__group__double-field__group--right
          .main-page__body__form__group__double-field__group__field-box
            .main-page__body__form__group__double-field__group__field-box__title
              タスク検索
            .main-page__body__form__group__double-field__group__field-box__field
              %input#task-search-input.main-page__body__form__group__double-field__group__field-box__field__input{ placeholder: "プロジェクト名を検索", type: "text" }
          #task-search-list.main-page__body__form__group__double-field__group__field-box.main-page__body__form__group__double-field__group__field-box--list-box
    - else
      .main-page__body__form__group__field
        = link_to "このプロジェクトに参加する", "", class: "main-page__body__form__group__field__submit-btn"